# Generated by Django 5.0.1 on 2024-01-23 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rooms',
        ),
    ]
